
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox8;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Entry entryBox;

	private global::Gtk.Table table5;

	private global::Gtk.Button btn;

	private global::Gtk.Button btn1;

	private global::Gtk.Button btn2;

	private global::Gtk.Button btn3;

	private global::Gtk.Button btn4;

	private global::Gtk.Button btn5;

	private global::Gtk.Button btn6;

	private global::Gtk.Button btn7;

	private global::Gtk.Button btn8;

	private global::Gtk.Button btn9;

	private global::Gtk.Button clearBtn;

	private global::Gtk.Button divideBtn;

	private global::Gtk.Button dotBtn;

	private global::Gtk.Button equalBtn;

	private global::Gtk.Button minusBtn;

	private global::Gtk.Button multiplyBtn;

	private global::Gtk.Button percentageBtn;

	private global::Gtk.Button plusBtn;

	private global::Gtk.Button plusMinusBtn;

	private global::Gtk.Button sqrtBtn1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(18));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.entryBox = new global::Gtk.Entry();
		this.entryBox.HeightRequest = 55;
		this.entryBox.CanFocus = true;
		this.entryBox.Name = "entryBox";
		this.entryBox.Text = global::Mono.Unix.Catalog.GetString("2 + 4");
		this.entryBox.IsEditable = false;
		this.entryBox.InvisibleChar = '●';
		this.vbox9.Add(this.entryBox);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.entryBox]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		this.vbox8.Add(this.vbox9);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox9]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.table5 = new global::Gtk.Table(((uint)(5)), ((uint)(4)), false);
		this.table5.HeightRequest = 350;
		this.table5.Name = "table5";
		// Container child table5.Gtk.Table+TableChild
		this.btn = new global::Gtk.Button();
		this.btn.CanFocus = true;
		this.btn.Name = "btn";
		this.btn.UseUnderline = true;
		this.btn.Label = global::Mono.Unix.Catalog.GetString("0");
		this.table5.Add(this.btn);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table5[this.btn]));
		w3.TopAttach = ((uint)(4));
		w3.BottomAttach = ((uint)(5));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		// Container child table5.Gtk.Table+TableChild
		this.btn1 = new global::Gtk.Button();
		this.btn1.CanFocus = true;
		this.btn1.Name = "btn1";
		this.btn1.UseUnderline = true;
		this.btn1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table5.Add(this.btn1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table5[this.btn1]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		// Container child table5.Gtk.Table+TableChild
		this.btn2 = new global::Gtk.Button();
		this.btn2.CanFocus = true;
		this.btn2.Name = "btn2";
		this.btn2.UseUnderline = true;
		this.btn2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table5.Add(this.btn2);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5[this.btn2]));
		w5.TopAttach = ((uint)(3));
		w5.BottomAttach = ((uint)(4));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		// Container child table5.Gtk.Table+TableChild
		this.btn3 = new global::Gtk.Button();
		this.btn3.CanFocus = true;
		this.btn3.Name = "btn3";
		this.btn3.UseUnderline = true;
		this.btn3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table5.Add(this.btn3);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table5[this.btn3]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		// Container child table5.Gtk.Table+TableChild
		this.btn4 = new global::Gtk.Button();
		this.btn4.CanFocus = true;
		this.btn4.Name = "btn4";
		this.btn4.UseUnderline = true;
		this.btn4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table5.Add(this.btn4);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table5[this.btn4]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		// Container child table5.Gtk.Table+TableChild
		this.btn5 = new global::Gtk.Button();
		this.btn5.CanFocus = true;
		this.btn5.Name = "btn5";
		this.btn5.UseUnderline = true;
		this.btn5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table5.Add(this.btn5);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table5[this.btn5]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		// Container child table5.Gtk.Table+TableChild
		this.btn6 = new global::Gtk.Button();
		this.btn6.CanFocus = true;
		this.btn6.Name = "btn6";
		this.btn6.UseUnderline = true;
		this.btn6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table5.Add(this.btn6);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table5[this.btn6]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		// Container child table5.Gtk.Table+TableChild
		this.btn7 = new global::Gtk.Button();
		this.btn7.CanFocus = true;
		this.btn7.Name = "btn7";
		this.btn7.UseUnderline = true;
		this.btn7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table5.Add(this.btn7);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table5[this.btn7]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		// Container child table5.Gtk.Table+TableChild
		this.btn8 = new global::Gtk.Button();
		this.btn8.CanFocus = true;
		this.btn8.Name = "btn8";
		this.btn8.UseUnderline = true;
		this.btn8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table5.Add(this.btn8);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table5[this.btn8]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		// Container child table5.Gtk.Table+TableChild
		this.btn9 = new global::Gtk.Button();
		this.btn9.CanFocus = true;
		this.btn9.Name = "btn9";
		this.btn9.UseUnderline = true;
		this.btn9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table5.Add(this.btn9);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table5[this.btn9]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		// Container child table5.Gtk.Table+TableChild
		this.clearBtn = new global::Gtk.Button();
		this.clearBtn.CanFocus = true;
		this.clearBtn.Name = "clearBtn";
		this.clearBtn.UseUnderline = true;
		this.clearBtn.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.table5.Add(this.clearBtn);
		// Container child table5.Gtk.Table+TableChild
		this.divideBtn = new global::Gtk.Button();
		this.divideBtn.CanFocus = true;
		this.divideBtn.Name = "divideBtn";
		this.divideBtn.UseUnderline = true;
		this.divideBtn.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table5.Add(this.divideBtn);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table5[this.divideBtn]));
		w14.LeftAttach = ((uint)(3));
		w14.RightAttach = ((uint)(4));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.dotBtn = new global::Gtk.Button();
		this.dotBtn.CanFocus = true;
		this.dotBtn.Name = "dotBtn";
		this.dotBtn.UseUnderline = true;
		this.dotBtn.Label = global::Mono.Unix.Catalog.GetString(".");
		this.table5.Add(this.dotBtn);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table5[this.dotBtn]));
		w15.TopAttach = ((uint)(4));
		w15.BottomAttach = ((uint)(5));
		w15.LeftAttach = ((uint)(2));
		w15.RightAttach = ((uint)(3));
		// Container child table5.Gtk.Table+TableChild
		this.equalBtn = new global::Gtk.Button();
		this.equalBtn.CanFocus = true;
		this.equalBtn.Name = "equalBtn";
		this.equalBtn.UseUnderline = true;
		this.equalBtn.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table5.Add(this.equalBtn);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table5[this.equalBtn]));
		w16.TopAttach = ((uint)(4));
		w16.BottomAttach = ((uint)(5));
		w16.LeftAttach = ((uint)(3));
		w16.RightAttach = ((uint)(4));
		// Container child table5.Gtk.Table+TableChild
		this.minusBtn = new global::Gtk.Button();
		this.minusBtn.CanFocus = true;
		this.minusBtn.Name = "minusBtn";
		this.minusBtn.UseUnderline = true;
		this.minusBtn.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table5.Add(this.minusBtn);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table5[this.minusBtn]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.LeftAttach = ((uint)(3));
		w17.RightAttach = ((uint)(4));
		// Container child table5.Gtk.Table+TableChild
		this.multiplyBtn = new global::Gtk.Button();
		this.multiplyBtn.CanFocus = true;
		this.multiplyBtn.Name = "multiplyBtn";
		this.multiplyBtn.UseUnderline = true;
		this.multiplyBtn.Label = global::Mono.Unix.Catalog.GetString("x");
		this.table5.Add(this.multiplyBtn);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table5[this.multiplyBtn]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(3));
		w18.RightAttach = ((uint)(4));
		// Container child table5.Gtk.Table+TableChild
		this.percentageBtn = new global::Gtk.Button();
		this.percentageBtn.CanFocus = true;
		this.percentageBtn.Name = "percentageBtn";
		this.percentageBtn.UseUnderline = true;
		this.percentageBtn.Label = global::Mono.Unix.Catalog.GetString("%");
		this.table5.Add(this.percentageBtn);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table5[this.percentageBtn]));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		// Container child table5.Gtk.Table+TableChild
		this.plusBtn = new global::Gtk.Button();
		this.plusBtn.CanFocus = true;
		this.plusBtn.Name = "plusBtn";
		this.plusBtn.UseUnderline = true;
		this.plusBtn.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table5.Add(this.plusBtn);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table5[this.plusBtn]));
		w20.TopAttach = ((uint)(3));
		w20.BottomAttach = ((uint)(4));
		w20.LeftAttach = ((uint)(3));
		w20.RightAttach = ((uint)(4));
		// Container child table5.Gtk.Table+TableChild
		this.plusMinusBtn = new global::Gtk.Button();
		this.plusMinusBtn.CanFocus = true;
		this.plusMinusBtn.Name = "plusMinusBtn";
		this.plusMinusBtn.UseUnderline = true;
		this.plusMinusBtn.Label = global::Mono.Unix.Catalog.GetString("+/-");
		this.table5.Add(this.plusMinusBtn);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table5[this.plusMinusBtn]));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		// Container child table5.Gtk.Table+TableChild
		this.sqrtBtn1 = new global::Gtk.Button();
		this.sqrtBtn1.CanFocus = true;
		this.sqrtBtn1.Name = "sqrtBtn1";
		this.sqrtBtn1.UseUnderline = true;
		this.sqrtBtn1.Label = global::Mono.Unix.Catalog.GetString("sqrt");
		this.table5.Add(this.sqrtBtn1);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table5[this.sqrtBtn1]));
		w22.TopAttach = ((uint)(4));
		w22.BottomAttach = ((uint)(5));
		this.vbox8.Add(this.table5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.table5]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.Add(this.vbox8);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 326;
		this.DefaultHeight = 447;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.sqrtBtn1.Clicked += new global::System.EventHandler(this.clickSqrt);
		this.plusMinusBtn.Clicked += new global::System.EventHandler(this.clickPlusMinus);
		this.plusBtn.Clicked += new global::System.EventHandler(this.clickAdd);
		this.percentageBtn.Clicked += new global::System.EventHandler(this.clickModulo);
		this.multiplyBtn.Clicked += new global::System.EventHandler(this.clickMultiply);
		this.minusBtn.Clicked += new global::System.EventHandler(this.clickMinus);
		this.equalBtn.Clicked += new global::System.EventHandler(this.clickEqual);
		this.dotBtn.Clicked += new global::System.EventHandler(this.clickDot);
		this.divideBtn.Clicked += new global::System.EventHandler(this.clickDivide);
		this.clearBtn.Clicked += new global::System.EventHandler(this.clickClear);
		this.btn9.Clicked += new global::System.EventHandler(this.clickNine);
		this.btn8.Clicked += new global::System.EventHandler(this.clickEight);
		this.btn7.Clicked += new global::System.EventHandler(this.clickSeven);
		this.btn6.Clicked += new global::System.EventHandler(this.clickSix);
		this.btn5.Clicked += new global::System.EventHandler(this.clickFive);
		this.btn4.Clicked += new global::System.EventHandler(this.clickFour);
		this.btn3.Clicked += new global::System.EventHandler(this.clickThree);
		this.btn2.Clicked += new global::System.EventHandler(this.clickTwo);
		this.btn1.Clicked += new global::System.EventHandler(this.clickedOne);
		this.btn.Clicked += new global::System.EventHandler(this.clickZero);
	}
}
